--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Pinesolz/Honey
build-by-default: true
branches:
- main
projects:
  Honey:
    path: ""
    icon: "icon.jpg"
    libs:
      - src: muqsit/invmenu/invmenu
        version: ^4.1.1
...
