---
#
#     /$$$$$$                      /$$          
#    /$$__  $$                    | $$          
#   | $$  \__/  /$$$$$$  /$$   /$$| $$ /$$$$$$$$
#   |  $$$$$$  /$$__  $$| $$  | $$| $$|____ /$$/
#    \____  $$| $$  \ $$| $$  | $$| $$   /$$$$/ 
#    /$$  \ $$| $$  | $$| $$  | $$| $$  /$$__/  
#   |  $$$$$$/|  $$$$$$/|  $$$$$$/| $$ /$$$$$$$$
#    \______/  \______/  \______/ |__/|________/
#
#   Honey Configuraton
#     (Pocketmine Economy)

# Use tag "{honey}" to display players amount of honey.

messages:
  # What player recieves on command execution "/honey"
  honey-count: "&aYou have {honey}"!


# Custom Enchant Name
ce-name: "Honey++"
# Custom Enchant Id (You can now mix it with other custom enchant plugins)
ce-id: 200
# What is the max ce-level?
max-level: 10
# How often will the ce activate?
chance: 20 # your ## / 100%  practically


shop:
  # You can go up to 53 keys || (Double Chest Inventory)
  # Start at 0 for the first slot.
  # Lore doesn't determine prices.
  0:
    id: 274 # Item Id || (Of item purchased)
    meta: 0 # Item Meta || (0 = Default)
    name: "&bTikTok" # Item Name
    lore:
      - "&r&dPrice - 2 Gems" # Lore One
      - "&r&aLore Line Two" # Lore Two
    price: 2 # How much honey will it take
    count: 1 # How many items
  1:
    id: 276
    meta: 0
    name: "&bInstagram"
    lore:
      - "&dPrice - 20 Gems"
      - "&r&d!"
      - "&r&c!"
      - "&r&6!"
    price: 20
    count: 1
...
